### ISSUE TITLE
RR_duino_net_serial.py: Recovering node causes other nodes to show down.

### ISSUE THREAD

**Issue by ggee** [manu-fwi/openlcb-gateway#4]
After a node has been down, when it is recovering, the other node(s) in the network briefly show as down.

Reproduce: unplug one node, wait a bit and plug back in.

On the good nodes, I briefly see the RX/TX LEDs pause until.

**Comment by manu-fwi** [comment]
I hope to tackle this in the coming days.

**Comment by manu-fwi** [comment]
Can you check out this tree and test if this bug is still there (I have fixed a nasty bug and hopefully everything should work as expected now).

**Comment by manu-fwi** [comment]
More fixes went in today. I will hammer it a bit more (I corrected a few more bugs already)

**Comment by ggee** [comment]
Sent an email with details.  I still see this particular issue.

**Comment by ggee** [comment]
Issue fixed.
